version: '3'
networks:
  web:
services:
  frontend:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../dist:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
